# This workflow will build a .NET project

name: Build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TrelloDotNet.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: SetUserSecretsTrelloApiKey        
      run: dotnet user-secrets set TrelloApiKey ${{ secrets.TRELLOAPIKEY }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj
    - name: SetUserSecretsTrelloApiKey2        
      run: dotnet user-secrets set TrelloApiKey2 ${{ secrets.TRELLOAPIKEY2 }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj
    - name: SetUserSecretsTrelloApiKey3        
      run: dotnet user-secrets set TrelloApiKey3 ${{ secrets.TRELLOAPIKEY3 }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj
    - name: SetUserSecretsTrelloApiKey4        
      run: dotnet user-secrets set TrelloApiKey4 ${{ secrets.TRELLOAPIKEY4 }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj
    - name: SetUserSecretsTrelloApiKey5        
      run: dotnet user-secrets set TrelloApiKey5 ${{ secrets.TRELLOAPIKEY5 }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj      
    - name: SetUserSecretsTrelloToken        
      run: dotnet user-secrets set TrelloToken ${{ secrets.TRELLOTOKEN }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj      
    - name: SetUserSecretsTrelloToken2        
      run: dotnet user-secrets set TrelloToken2 ${{ secrets.TRELLOTOKEN2 }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj      
    - name: SetUserSecretsTrelloToken3        
      run: dotnet user-secrets set TrelloToken3 ${{ secrets.TRELLOTOKEN3 }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj      
    - name: SetUserSecretsTrelloToken4        
      run: dotnet user-secrets set TrelloToken4 ${{ secrets.TRELLOTOKEN4 }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj      
    - name: SetUserSecretsTrelloToken5        
      run: dotnet user-secrets set TrelloToken5 ${{ secrets.TRELLOTOKEN5 }} --project src/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj            
    - name: Test      
      run: dotnet test --configuration Release --no-build --verbosity normal --p:CollectCoverage=true --p:CoverletOutput=TestResults/ --p:CoverletOutputFormat=lcov
      working-directory: src/TrelloDotNet.Tests
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: src/TrelloDotNet.Tests/TestResults/coverage.info
    - name: Publish to NuGet if needed
      run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
